### ISSUE TITLE
Hang on Loading 'Snatched & Available'''

### ISSUE THREAD

**Issue by mkools** [RuudBurger/CouchPotatoServer#4026]
Since the update it hangs when I click home on 'Loading 'Snatched & Available'.

Log file pasted below.

### Steps to reproduce:
1. Restart Couchpotato
2. Go to home

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) b773f7b7 (2014-10-07 23:09:44)
Running on: ...

### Logs:
```
10-07 23:25:18 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "/opt/CouchPotatoServer/couchpotato/api.py", line 144, in taskFinished
    self.write(result)
  File "/opt/CouchPotatoServer/libs/tornado/web.py", line 658, in write
    chunk = escape.json_encode(chunk)
  File "/opt/CouchPotatoServer/libs/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 220: invalid start byte 
```

**Comment by sverr1** [comment]
I had the problem. Fixed it by deleting the old install and getting a new one and just transfered over the settings file. Now the issue is back. 

### Steps to reproduce:
1. Open CP

### Information:
Movie(s) I have this with: CP it self. Haven't noticed anything particular.
Quality of the movie being searched: 1080p
Providers I use: dognzb and torrentbytes
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 0288cc88 (2014-12-22 22:02:05)
Running on: newest debian up-to-date

### Logs:
```
01-01 18:13:01 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "/home/sverre/mediaserver/CP/couchpotato/api.py", line 147, in sendData
    self.finish(result)
  File "/home/sverre/mediaserver/CP/libs/tornado/web.py", line 866, in finish
    self.write(chunk)
  File "/home/sverre/mediaserver/CP/libs/tornado/web.py", line 655, in write
    chunk = escape.json_encode(chunk)
  File "/home/sverre/mediaserver/CP/libs/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 220: invalid start byte 
```

**Comment by DcR-NL** [comment]
I've completely removed my installation, pulled the latest master commit (2f5526d5) and moved my *settings.conf* file back. I didn't migrate the database. But after adding two movies to my wanted list the error reappeared again.

My previous report: https://github.com/RuudBurger/CouchPotatoServer/issues/4414#issuecomment-68524273

New full log after reinstall: http://pastebin.com/qnnPxXBK

**Comment by AGresvig** [comment]
I'm experiencing it too, with latest CP version. I had it a few revisions ago, then it was fixed, and now it came back in one of the later releases. Frustrating.

**Comment by sinom** [comment]
Same here, still having this issue. Any news on the subject would be swell.

**Comment by sverr1** [comment]
I disabled Torrentbytes and I'm not seeing any problems right now. Other info; Sick* stopped giving me the unicode error even though Torrentbytes is still enabled.

**Comment by DcR-NL** [comment]
@sinom 
Disabling TorrentBytes and starting with a new database seems to have 'fixed' it for me... Would like to recommend doing this till the provider fetching is fixed.

This is what I did:
1. Disable TorrentBytes from the WebUI;
2. Take note of your quality settings (because they are saved to the database);
3. Shutdown CP;
4. Copy the **settings.conf** file to a safe location;
5. Remove CP completely;
6. Reinstall/fetch the latest master branch;
7. Make sure CP is not running and copy the **settings.conf** file back;
8. Run CP.

@sverr1
The utf-8 error was fixed for SickRage (SickBeard fork) a couple of weeks back...

**Comment by sverr1** [comment]
@DcR-NL I've moved over to SickGear. They probably just added the fix :)) Your fix was what I did too.

**Comment by RuudBurger** [comment]
A full re-search should fix the issue

**Comment by AGresvig** [comment]
Seems to work, thanks!

Thu Jan 08 2015 at 4:59:04 PM skrev Ruud Burger <notifications@github.com>:

**Comment by ben-joostens** [comment]
Still happening for me on the latest version and after a full library refresh.

**Comment by ChristianP82** [comment]
I also have this problem again with version 9964d959 (1/8/2015, 4:57:03 PM).

**Comment by ben-joostens** [comment]
Anything we can do to help you find the issue? Cause we're basically left with a broken installation.

**Comment by RuudBurger** [comment]
Please send me a zip of your database.

**Comment by ben-joostens** [comment]
Now all of a sudden it's working again…

**Comment by Popupkiller** [comment]
Is this something that was fixed? I just downloaded 3.0.1, and I have never used this application before.
I install it through the exe installer, and choose to start it now, and it shows me a blank screen.
