### ISSUE TITLE
Couchpotato User Script Extension 1.0.2 (Chrome) stuck "Loading Movie Info"

### ISSUE THREAD

**Issue by zx3junglist** [RuudBurger/CouchPotatoServer#4464]
From IMDB, when clicking the user script icon, the panel slides out from the right and says "Loading Movie Info" and remains. The console says:

"Error in event handler for (unknown): TypeError: Cannot read property 'poster_original' of undefined
    at Object.queryApi.onComplete (eval at <anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:1:169), <anonymous>:1504:28)
    at eval (eval at <anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:1:169), <anonymous>:1683:14)
    at chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:3:3
    at Object.d.onSuccess (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:19:13)
    at Object.n [as KangoInvokeAsyncModule_result] (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:17:425)
    at Array.<anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:18:226)
    at chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:13:292"

**Comment by RuudBurger** [comment]
Should be fixed in 1.1.2

**Comment by zx3junglist** [comment]
Installed 1.1.2, still having the problem. Couchpotato log for "The Hunger Games: Catching Fire (2013)" shows the following (however other movies also have this issue):

`01-05 17:33:05 INFO [e.providers.movie.imdbapi] Found: The Hunger Games: Catching Fire (2013)01-05 17:33:06 ERROR [hpotato.core.plugins.base] Failed opening url in CouchPotatoApi: https://couchpota.to/api/info/tt1951264/ Traceback (most recent call last):
  File "/home/ubu-server/.couchpotato/couchpotato/core/plugins/base.py", line 148, in urlopen
    response = urllib2.urlopen(request, timeout = timeout)
HTTPError: HTTP Error 404: Not Found
01-05 17:33:06 DEBUG [ couchpotato.core.event] Return modified results for movie.info`

The console output from Chrome shows:

`01-05 17:33:05 INFO [e.providers.movie.imdbapi] Found: The Hunger Games: Catching Fire (2013)01-05 17:33:06 ERROR [hpotato.core.plugins.base] Failed opening url in CouchPotatoApi: https://couchpota.to/api/info/tt1951264/ Traceback (most recent call last):
  File "/home/ubu-server/.couchpotato/couchpotato/core/plugins/base.py", line 148, in urlopen
    response = urllib2.urlopen(request, timeout = timeout)
HTTPError: HTTP Error 404: Not Found
01-05 17:33:06 DEBUG [ couchpotato.core.event] Return modified results for movie.info`

**Comment by RuudBurger** [comment]
You need to update your cp. More then 1 year behind.;)

**Comment by zx3junglist** [comment]
Isn't this the new version:
Version2f5526d57ee3601c3d465a631b16b5e47fd3b88e (1/2/2015, 5:54:36 PM)
The version of the extension in the chrome extension web store is 1.1.2. Using the couchpotato UI to install the script no longer works in chrome due to security changes.

**Comment by RuudBurger** [comment]
https://couchpota.to/api/ isn't the API URL for more then a year. So double check your install.
